[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  CI = "false"

[functions]
  directory = "netlify/functions"
  node_bundler = "zisi"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
